--CREATE EMPLOYEE TABLE
CREATE TABLE EMPLOYEE
(
EMPLOYEEID int IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMPLOYEENAME VARCHAR(50),
EMPLOYEEADDRESS VARCHAR(50),
EMPLOYEECITY VARCHAR(50),
EMPLOYEENUMBER NVARCHAR(50),
EMPLOYEESALARY NVARCHAR(50)
)

INSERT INTO EMPLOYEE (EMPLOYEENAME, EMPLOYEEADDRESS, EMPLOYEECITY, EMPLOYEENUMBER, EMPLOYEESALARY) VALUES ('SUCHINDRA', 'DOMBIVLI', 'THANE', 9078651423, 400000) 

SET STATISTICS IO ON
SET STATISTICS TIME ON
SELECT EMPLOYEEID, EMPLOYEENAME, EMPLOYEENUMBER, EMPLOYEESALARY FROM EMPLOYEE WHERE EMPLOYEENAME LIKE 'SU%'
SET STATISTICS IO OFF
SET STATISTICS TIME OFF


--CREATE EMPLOYEE TABLE
CREATE TABLE EMPLOYEEREPORT
(
EMPLOYEEREPORT int IDENTITY (1,1) PRIMARY KEY NOT NULL,
EMPLOYEENUMBER NVARCHAR(50),
EMPLOYEESALARY NVARCHAR(50)
)


INSERT INTO EMPLOYEEREPORT
(
EMPLOYEENUMBER, 
EMPLOYEESALARY
)
SELECT EMPLOYEENUMBER, EMPLOYEESALARY FROM EMPLOYEE

SET STATISTICS IO ON
SET STATISTICS TIME ON
SELECT EMPLOYEENUMBER, EMPLOYEESALARY FROM EMPLOYEEREPORT WHERE EMPLOYEENUMBER LIKE '90%'
SET STATISTICS IO OFF
SET STATISTICS TIME OFF


ALTER DATABASE demo
ADD FILEGROUP Report1
GO

ALTER DATABASE demo
ADD FILEGROUP Report2
GO

ALTER DATABASE demo
ADD FILEGROUP Report3
GO

ALTER DATABASE demo
ADD FILEGROUP Report4
GO



SELECT NAME AS AVAILABLEFILEGROUPS
FROM sys.filegroups
WHERE type = 'FG'


ALTER DATABASE [demo]
ADD FILE
(
NAME = [Data],
FILENAME = 'C:\Users\suchi\Downloads\data.csv',
SIZE = 3814 KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024 KB
) TO FILEGROUP [Report1]